# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

systematic_resampling_ <- function(nsamples, weights) {
    .Call('_montecarlodsm_systematic_resampling_', PACKAGE = 'montecarlodsm', nsamples, weights)
}

multinomial_resampling_ <- function(nsamples, weights) {
    .Call('_montecarlodsm_multinomial_resampling_', PACKAGE = 'montecarlodsm', nsamples, weights)
}

SSP_resampling_ <- function(nsamples, weights) {
    .Call('_montecarlodsm_SSP_resampling_', PACKAGE = 'montecarlodsm', nsamples, weights)
}

runif_piktheta_cpp <- function(n, k, theta) {
    .Call('_montecarlodsm_runif_piktheta_cpp', PACKAGE = 'montecarlodsm', n, k, theta)
}

